export const destinations = [
  {
    id: 'santorini',
    name: 'Santorini',
    country: 'Greece',
    continent: 'Europe',
    emoji: '🇬🇷',
    category: 'Coastal',
    lat: 36.3932,
    lon: 25.4615,
    timeZone: 'Europe/Athens',
    wikiTitle: 'Santorini',
    intro: 'Whitewashed villages, volcanic cliffs, and blue-domed churches above the Aegean Sea.',
    fact: 'Santorini sits on the rim of a massive volcanic caldera formed by a major ancient eruption.',
    accent: 'sunset'
  },
  {
    id: 'socotra',
    name: 'Socotra',
    country: 'Yemen',
    continent: 'Asia',
    emoji: '🇾🇪',
    category: 'Wild',
    lat: 12.4634,
    lon: 53.8237,
    timeZone: 'Asia/Aden',
    wikiTitle: 'Socotra',
    intro: 'Dragon blood trees and remote beaches make Socotra feel like another planet.',
    fact: 'A large share of Socotra’s native plant life is found nowhere else on Earth.',
    accent: 'wild'
  },
  {
    id: 'shirakawa',
    name: 'Shirakawa-go',
    country: 'Japan',
    continent: 'Asia',
    emoji: '🇯🇵',
    category: 'Culture',
    lat: 36.2606,
    lon: 136.9062,
    timeZone: 'Asia/Tokyo',
    wikiTitle: 'Historic Villages of Shirakawa-gō and Gokayama',
    intro: 'A mountain village known for steep thatched-roof farmhouses built to survive heavy snow.',
    fact: 'Its traditional gassho-zukuri roofs resemble hands pressed together in prayer.',
    accent: 'snow'
  },
  {
    id: 'sossusvlei',
    name: 'Sossusvlei',
    country: 'Namibia',
    continent: 'Africa',
    emoji: '🇳🇦',
    category: 'Desert',
    lat: -24.7275,
    lon: 15.2924,
    timeZone: 'Africa/Windhoek',
    wikiTitle: 'Sossusvlei',
    intro: 'Towering red dunes rise around pale salt pans deep inside the Namib Desert.',
    fact: 'Some dunes in the area rank among the tallest in the world.',
    accent: 'desert'
  },
  {
    id: 'banff',
    name: 'Banff',
    country: 'Canada',
    continent: 'North America',
    emoji: '🇨🇦',
    category: 'Mountains',
    lat: 51.1784,
    lon: -115.5708,
    timeZone: 'America/Edmonton',
    wikiTitle: 'Banff National Park',
    intro: 'Turquoise lakes, dramatic peaks, and evergreen forests define this Rocky Mountain destination.',
    fact: 'Banff became Canada’s first national park in 1885.',
    accent: 'alpine'
  },
  {
    id: 'lencois',
    name: 'Lençóis Maranhenses',
    country: 'Brazil',
    continent: 'South America',
    emoji: '🇧🇷',
    category: 'Rare',
    lat: -2.5333,
    lon: -43.1167,
    timeZone: 'America/Fortaleza',
    wikiTitle: 'Lençóis Maranhenses National Park',
    intro: 'Sweeping white dunes fill with seasonal freshwater lagoons after the rains.',
    fact: 'Despite looking like a desert, the region receives substantial seasonal rainfall.',
    accent: 'lagoon'
  },
  {
    id: 'cappadocia',
    name: 'Cappadocia',
    country: 'Türkiye',
    continent: 'Asia',
    emoji: '🇹🇷',
    category: 'Culture',
    lat: 38.6431,
    lon: 34.8289,
    timeZone: 'Europe/Istanbul',
    wikiTitle: 'Cappadocia',
    intro: 'Fairy chimneys, cave homes, and sunrise balloons create a surreal volcanic landscape.',
    fact: 'Ancient communities carved entire underground cities into the soft volcanic rock.',
    accent: 'rose'
  },
  {
    id: 'lofoten',
    name: 'Lofoten',
    country: 'Norway',
    continent: 'Europe',
    emoji: '🇳🇴',
    category: 'Mountains',
    lat: 68.2089,
    lon: 13.9154,
    timeZone: 'Europe/Oslo',
    wikiTitle: 'Lofoten',
    intro: 'Sharp peaks rise straight from the sea beside fishing villages and Arctic beaches.',
    fact: 'Despite its northern latitude, ocean currents keep Lofoten milder than many places this far north.',
    accent: 'arctic'
  }
];

export const categories = ['All', 'Coastal', 'Wild', 'Culture', 'Desert', 'Mountains', 'Rare'];
