export const destinations = [
  {
    "id": "santorini",
    "name": "Santorini",
    "country": "Greece",
    "continent": "Europe",
    "emoji": "🇬🇷",
    "category": "Coastal",
    "lat": 36.3932,
    "lon": 25.4615,
    "timeZone": "Europe/Athens",
    "wikiTitle": "Santorini",
    "accent": "sunset",
    "intro": "Whitewashed villages, volcanic cliffs and blue-domed churches above the Aegean Sea.",
    "fact": "Santorini sits on the rim of a volcanic caldera.",
    "knownFor": [
      "Caldera sunsets",
      "Whitewashed cliff villages",
      "Assyrtiko wine"
    ],
    "unique": "Homes, churches and paths are built into volcanic terrain, giving the island its dramatic layered shape.",
    "culture": "Island life blends Orthodox traditions, seafaring history, cave architecture and a strong wine culture.",
    "museum": "Museum of Prehistoric Thera, Archaeological Museum of Thera, Maritime Museum, Wine Museum",
    "food": "Tomatokeftedes, fava, white eggplant and local Assyrtiko wine.",
    "language": "Greek",
    "greeting": "Γεια σου! (Yia sou!)",
    "goodbye": "Αντίο! (Adío!)",
    "guide": {
      "name": "Nefeli",
      "emoji": "🐱",
      "line": "I’m Nefeli, your island cat. Follow me past the blue domes and into Santorini’s volcanic story."
    }
  },
  {
    "id": "athens",
    "name": "Athens",
    "country": "Greece",
    "continent": "Europe",
    "emoji": "🇬🇷",
    "category": "Culture",
    "lat": 37.9838,
    "lon": 23.7275,
    "timeZone": "Europe/Athens",
    "wikiTitle": "Athens",
    "accent": "sunset",
    "intro": "Ancient ruins and lively neighbourhoods share the same streets in Greece’s capital.",
    "fact": "The Acropolis has shaped Athens’ skyline for more than two millennia.",
    "knownFor": [
      "Acropolis",
      "Classical history",
      "Neighbourhood tavernas"
    ],
    "unique": "Few cities let you walk from ancient temples to contemporary street art in minutes.",
    "culture": "Greek social life often centers on long meals, coffee, music and evening strolls.",
    "museum": "Acropolis Museum, National Archaeological Museum, Benaki Museum",
    "food": "Souvlaki, spanakopita, grilled seafood and loukoumades.",
    "language": "Greek",
    "greeting": "Γεια σου! (Yia sou!)",
    "goodbye": "Τα λέμε! (Ta léme!)",
    "guide": {
      "name": "Piko",
      "emoji": "🦉",
      "line": "I’m Piko the little owl. Athens loves old stories, but it never stopped making new ones."
    }
  },
  {
    "id": "rome",
    "name": "Rome",
    "country": "Italy",
    "continent": "Europe",
    "emoji": "🇮🇹",
    "category": "Culture",
    "lat": 41.9028,
    "lon": 12.4964,
    "timeZone": "Europe/Rome",
    "wikiTitle": "Rome",
    "accent": "rose",
    "intro": "Imperial ruins, fountains, piazzas and neighbourhood life make Rome feel like an open-air museum.",
    "fact": "Ancient, Renaissance, Baroque and modern Rome overlap across the same urban fabric.",
    "knownFor": [
      "Colosseum",
      "Roman Forum",
      "Piazzas and fountains"
    ],
    "unique": "Archaeological remains are woven directly into everyday city life.",
    "culture": "The passeggiata, café culture, family meals and neighbourhood identity remain central.",
    "museum": "Capitoline Museums, Galleria Borghese, Vatican Museums",
    "food": "Carbonara, cacio e pepe, supplì and gelato.",
    "language": "Italian",
    "greeting": "Ciao!",
    "goodbye": "Arrivederci!",
    "guide": {
      "name": "Luna",
      "emoji": "🐺",
      "line": "Ciao! I’m Luna. Rome is best explored one piazza, ruin and plate of pasta at a time."
    }
  },
  {
    "id": "venice",
    "name": "Venice",
    "country": "Italy",
    "continent": "Europe",
    "emoji": "🇮🇹",
    "category": "Coastal",
    "lat": 45.4408,
    "lon": 12.3155,
    "timeZone": "Europe/Rome",
    "wikiTitle": "Venice",
    "accent": "lagoon",
    "intro": "A city of canals, bridges, palaces and tiny alleys built across a lagoon.",
    "fact": "Venice developed across more than a hundred small islands linked by bridges.",
    "knownFor": [
      "Canals",
      "Gondolas",
      "Carnival masks"
    ],
    "unique": "There are no ordinary roads through the historic core; boats and walking define movement.",
    "culture": "Glassmaking, mask-making, maritime trade and neighbourhood traditions shape Venetian identity.",
    "museum": "Doge’s Palace, Peggy Guggenheim Collection, Museo Correr",
    "food": "Cicchetti, sarde in saor, risotto al nero di seppia.",
    "language": "Italian",
    "greeting": "Ciao!",
    "goodbye": "A presto!",
    "guide": {
      "name": "Bricola",
      "emoji": "🪽",
      "line": "Ciao! I’m Bricola, named after the wooden posts in the lagoon. Let’s get wonderfully lost."
    }
  },
  {
    "id": "paris",
    "name": "Paris",
    "country": "France",
    "continent": "Europe",
    "emoji": "🇫🇷",
    "category": "Culture",
    "lat": 48.8566,
    "lon": 2.3522,
    "timeZone": "Europe/Paris",
    "wikiTitle": "Paris",
    "accent": "rose",
    "intro": "Art, architecture, cafés and neighbourhood life make Paris more than its famous monuments.",
    "fact": "Paris has one of the world’s densest concentrations of museums and historic monuments.",
    "knownFor": [
      "Eiffel Tower",
      "Museums",
      "Café culture"
    ],
    "unique": "Grand boulevards, intimate quartiers and world-scale art institutions coexist within a walkable core.",
    "culture": "Terrace cafés, markets, fashion, literature and long-standing neighbourhood identities define daily life.",
    "museum": "Louvre, Musée d’Orsay, Musée Carnavalet, Centre Pompidou",
    "food": "Croissants, baguettes, cheese, crêpes and pastries.",
    "language": "French",
    "greeting": "Bonjour!",
    "goodbye": "Au revoir!",
    "guide": {
      "name": "Mimi",
      "emoji": "🐈",
      "line": "Bonjour! I’m Mimi. Paris rewards curiosity—especially when you wander one street beyond the postcard."
    }
  },
  {
    "id": "barcelona",
    "name": "Barcelona",
    "country": "Spain",
    "continent": "Europe",
    "emoji": "🇪🇸",
    "category": "Culture",
    "lat": 41.3874,
    "lon": 2.1686,
    "timeZone": "Europe/Madrid",
    "wikiTitle": "Barcelona",
    "accent": "sunset",
    "intro": "Mediterranean beaches meet bold modernist architecture and Catalan street life.",
    "fact": "Antoni Gaudí’s architecture helped give Barcelona its instantly recognizable visual identity.",
    "knownFor": [
      "Gaudí",
      "Catalan culture",
      "Mediterranean life"
    ],
    "unique": "A single city combines Roman traces, medieval lanes, modernist blocks and urban beaches.",
    "culture": "Catalan language, castellers, markets, festivals and late-evening public life are important local markers.",
    "museum": "MNAC, Picasso Museum, Barcelona History Museum",
    "food": "Pa amb tomàquet, crema catalana, seafood and tapas.",
    "language": "Catalan / Spanish",
    "greeting": "Hola! / Bon dia!",
    "goodbye": "Adéu!",
    "guide": {
      "name": "Sol",
      "emoji": "🦎",
      "line": "Bon dia! I’m Sol, your mosaic gecko. Barcelona loves colour, curves and public life."
    }
  },
  {
    "id": "lisbon",
    "name": "Lisbon",
    "country": "Portugal",
    "continent": "Europe",
    "emoji": "🇵🇹",
    "category": "Coastal",
    "lat": 38.7223,
    "lon": -9.1393,
    "timeZone": "Europe/Lisbon",
    "wikiTitle": "Lisbon",
    "accent": "sunset",
    "intro": "Hills, tiled façades, yellow trams and the Tagus give Lisbon its distinctive rhythm.",
    "fact": "Fado is one of Lisbon’s defining musical traditions.",
    "knownFor": [
      "Fado",
      "Azulejo tiles",
      "Historic trams"
    ],
    "unique": "Steep viewpoints and tiled neighbourhoods create a cityscape that changes every few streets.",
    "culture": "Fado, neighbourhood festivals, riverfront life and café traditions remain central.",
    "museum": "Fado Museum, National Tile Museum, MAAT",
    "food": "Pastéis de nata, bacalhau, bifana and grilled sardines.",
    "language": "Portuguese",
    "greeting": "Olá!",
    "goodbye": "Até logo!",
    "guide": {
      "name": "Tico",
      "emoji": "🐦",
      "line": "Olá! I’m Tico. Listen closely—Lisbon tells its story through hills, tiles and songs."
    }
  },
  {
    "id": "vienna",
    "name": "Vienna",
    "country": "Austria",
    "continent": "Europe",
    "emoji": "🇦🇹",
    "category": "Culture",
    "lat": 48.2082,
    "lon": 16.3738,
    "timeZone": "Europe/Vienna",
    "wikiTitle": "Vienna",
    "accent": "rose",
    "intro": "Imperial architecture, music, museums and coffeehouses shape Vienna’s cultural identity.",
    "fact": "Vienna’s coffeehouse tradition is closely tied to the city’s literary and social history.",
    "knownFor": [
      "Classical music",
      "Imperial palaces",
      "Coffeehouses"
    ],
    "unique": "World-class music and art institutions sit beside everyday café culture.",
    "culture": "Concert-going, coffeehouse conversation and the legacy of the Habsburg court remain visible.",
    "museum": "Kunsthistorisches Museum, Albertina, Belvedere, House of Music",
    "food": "Wiener schnitzel, sachertorte, apfelstrudel and coffee.",
    "language": "German",
    "greeting": "Hallo!",
    "goodbye": "Auf Wiedersehen!",
    "guide": {
      "name": "Melo",
      "emoji": "🎼",
      "line": "Hallo! I’m Melo. Vienna likes its culture grand—but its best conversations often happen over coffee."
    }
  },
  {
    "id": "prague",
    "name": "Prague",
    "country": "Czechia",
    "continent": "Europe",
    "emoji": "🇨🇿",
    "category": "Culture",
    "lat": 50.0755,
    "lon": 14.4378,
    "timeZone": "Europe/Prague",
    "wikiTitle": "Prague",
    "accent": "rose",
    "intro": "Gothic towers, bridges, courtyards and music venues give Prague a theatrical skyline.",
    "fact": "Prague’s historic core preserves layers from medieval, Baroque and modern eras.",
    "knownFor": [
      "Charles Bridge",
      "Old Town",
      "Beer culture"
    ],
    "unique": "Dense architectural layers make the city feel like a timeline you can walk through.",
    "culture": "Theatre, classical music, puppetry and pub culture all have deep roots.",
    "museum": "National Museum, Museum of Decorative Arts, National Gallery Prague",
    "food": "Svíčková, dumplings, koláče and Czech lager.",
    "language": "Czech",
    "greeting": "Ahoj!",
    "goodbye": "Na shledanou!",
    "guide": {
      "name": "Kuba",
      "emoji": "🦔",
      "line": "Ahoj! I’m Kuba. Prague hides stories in towers, courtyards and old stone streets."
    }
  },
  {
    "id": "amsterdam",
    "name": "Amsterdam",
    "country": "Netherlands",
    "continent": "Europe",
    "emoji": "🇳🇱",
    "category": "Culture",
    "lat": 52.3676,
    "lon": 4.9041,
    "timeZone": "Europe/Amsterdam",
    "wikiTitle": "Amsterdam",
    "accent": "lagoon",
    "intro": "Canals, bicycles, narrow houses and major museums define Amsterdam’s character.",
    "fact": "Museumplein brings several internationally significant museums into one cultural district.",
    "knownFor": [
      "Canals",
      "Cycling",
      "Major art museums"
    ],
    "unique": "The canal belt creates a city structure where water, homes and public life are tightly interwoven.",
    "culture": "Cycling, neighbourhood markets, design and direct social culture are widely associated with the city.",
    "museum": "Rijksmuseum, Van Gogh Museum, Stedelijk Museum, Rembrandt House",
    "food": "Stroopwafels, bitterballen, herring and Dutch cheeses.",
    "language": "Dutch",
    "greeting": "Hallo!",
    "goodbye": "Tot ziens!",
    "guide": {
      "name": "Pip",
      "emoji": "🦆",
      "line": "Hallo! I’m Pip. In Amsterdam, the best route is often beside a canal rather than a road."
    }
  },
  {
    "id": "edinburgh",
    "name": "Edinburgh",
    "country": "United Kingdom",
    "continent": "Europe",
    "emoji": "🇬🇧",
    "category": "Culture",
    "lat": 55.9533,
    "lon": -3.1883,
    "timeZone": "Europe/London",
    "wikiTitle": "Edinburgh",
    "accent": "arctic",
    "intro": "A dramatic castle skyline, medieval lanes and festival culture define Scotland’s capital.",
    "fact": "Edinburgh’s Old and New Towns together form a UNESCO World Heritage Site.",
    "knownFor": [
      "Edinburgh Castle",
      "Festivals",
      "Old Town closes"
    ],
    "unique": "A volcanic landscape underpins a dense historic city of steep streets and dramatic views.",
    "culture": "Storytelling, literature, live performance and Scottish traditions are deeply visible.",
    "museum": "National Museum of Scotland, Scottish National Gallery, Writers’ Museum",
    "food": "Haggis, shortbread, Cullen skink and whisky.",
    "language": "English / Scottish Gaelic",
    "greeting": "Halò!",
    "goodbye": "Mar sin leat!",
    "guide": {
      "name": "Thistle",
      "emoji": "🦊",
      "line": "Halò! I’m Thistle. Edinburgh loves a good story—especially if it comes with mist and stone stairs."
    }
  },
  {
    "id": "reykjavik",
    "name": "Reykjavík",
    "country": "Iceland",
    "continent": "Europe",
    "emoji": "🇮🇸",
    "category": "Rare",
    "lat": 64.1466,
    "lon": -21.9426,
    "timeZone": "Atlantic/Reykjavik",
    "wikiTitle": "Reykjavík",
    "accent": "arctic",
    "intro": "Colourful houses, geothermal pools and strong arts culture sit on the edge of the North Atlantic.",
    "fact": "Reykjavík’s cultural scene is unusually dense for a relatively small capital.",
    "knownFor": [
      "Geothermal pools",
      "Nordic design",
      "Music and arts"
    ],
    "unique": "Urban life sits close to lava fields, sea, mountains and geothermal energy.",
    "culture": "Swimming pools function as social spaces, while literature and music are major parts of city life.",
    "museum": "National Museum of Iceland, Reykjavík Art Museum, Árbær Open Air Museum, Perlan",
    "food": "Lamb, fish, rye bread and skyr.",
    "language": "Icelandic",
    "greeting": "Halló!",
    "goodbye": "Bless!",
    "guide": {
      "name": "Funi",
      "emoji": "🐑",
      "line": "Halló! I’m Funi. Reykjavík is small, creative and never far from wild geology."
    }
  },
  {
    "id": "istanbul",
    "name": "Istanbul",
    "country": "Türkiye",
    "continent": "Europe / Asia",
    "emoji": "🇹🇷",
    "category": "Culture",
    "lat": 41.0082,
    "lon": 28.9784,
    "timeZone": "Europe/Istanbul",
    "wikiTitle": "Istanbul",
    "accent": "sunset",
    "intro": "Mosques, palaces, ferries and markets connect Europe and Asia across the Bosphorus.",
    "fact": "Istanbul has served as a capital of major empires under different names.",
    "knownFor": [
      "Bosphorus",
      "Hagia Sophia",
      "Grand Bazaar"
    ],
    "unique": "Few cities physically and culturally bridge two continents so visibly.",
    "culture": "Tea, ferry rides, bazaars, mosque courtyards and neighbourhood food culture shape daily rhythms.",
    "museum": "Topkapı Palace, Istanbul Archaeological Museums, Pera Museum",
    "food": "Simit, kebab, meze, baklava and Turkish tea.",
    "language": "Turkish",
    "greeting": "Merhaba!",
    "goodbye": "Hoşça kal!",
    "guide": {
      "name": "Mavi",
      "emoji": "🐈",
      "line": "Merhaba! I’m Mavi. Istanbul is a city of crossings—continents, empires, ferries and flavours."
    }
  },
  {
    "id": "cappadocia",
    "name": "Cappadocia",
    "country": "Türkiye",
    "continent": "Asia",
    "emoji": "🇹🇷",
    "category": "Rare",
    "lat": 38.6431,
    "lon": 34.8289,
    "timeZone": "Europe/Istanbul",
    "wikiTitle": "Cappadocia",
    "accent": "rose",
    "intro": "Fairy chimneys, cave dwellings and underground cities fill a surreal volcanic landscape.",
    "fact": "Soft volcanic rock allowed communities to carve churches, homes and underground settlements.",
    "knownFor": [
      "Fairy chimneys",
      "Cave churches",
      "Hot-air balloons"
    ],
    "unique": "Entire settlements were carved vertically into rock and underground.",
    "culture": "Regional craft, pottery, village life and cave architecture are central to the area’s identity.",
    "museum": "Göreme Open Air Museum, Zelve Open Air Museum",
    "food": "Testi kebabı, gözleme and regional wines.",
    "language": "Turkish",
    "greeting": "Merhaba!",
    "goodbye": "Güle güle!",
    "guide": {
      "name": "Puff",
      "emoji": "🎈",
      "line": "Merhaba! I’m Puff. Cappadocia is what happens when geology and human imagination collaborate for centuries."
    }
  },
  {
    "id": "petra",
    "name": "Petra",
    "country": "Jordan",
    "continent": "Asia",
    "emoji": "🇯🇴",
    "category": "Culture",
    "lat": 30.3285,
    "lon": 35.4444,
    "timeZone": "Asia/Amman",
    "wikiTitle": "Petra",
    "accent": "desert",
    "intro": "A Nabataean city carved into rose-coloured sandstone cliffs.",
    "fact": "Petra was a major caravan hub with sophisticated water-management systems.",
    "knownFor": [
      "The Treasury",
      "Nabataean engineering",
      "Rose sandstone"
    ],
    "unique": "Architecture is carved directly into cliffs while hidden channels once managed scarce water.",
    "culture": "Petra reflects Nabataean, regional Arab and later Roman influences tied to trade routes.",
    "museum": "Petra Museum",
    "food": "Mansaf, maqluba, mezze and mint tea.",
    "language": "Arabic",
    "greeting": "مرحباً! (Marhaban!)",
    "goodbye": "مع السلامة! (Ma’a salama!)",
    "guide": {
      "name": "Rami",
      "emoji": "🐪",
      "line": "Marhaban! I’m Rami. Petra is not just a façade—it was a living trade city with brilliant engineering."
    }
  },
  {
    "id": "cairo",
    "name": "Cairo",
    "country": "Egypt",
    "continent": "Africa",
    "emoji": "🇪🇬",
    "category": "Culture",
    "lat": 30.0444,
    "lon": 31.2357,
    "timeZone": "Africa/Cairo",
    "wikiTitle": "Cairo",
    "accent": "desert",
    "intro": "A vast city of Islamic architecture, Nile life and gateways to ancient Egyptian history.",
    "fact": "Historic Cairo contains one of the world’s great concentrations of Islamic monuments.",
    "knownFor": [
      "Egyptian Museum",
      "Historic Cairo",
      "Nearby Giza pyramids"
    ],
    "unique": "Pharaonic, Coptic, Islamic and modern layers sit within one metropolitan region.",
    "culture": "Café culture, family life, Ramadan traditions, music and street food are deeply visible.",
    "museum": "Grand Egyptian Museum, Egyptian Museum, National Museum of Egyptian Civilization",
    "food": "Koshari, ful medames, ta’ameya and kunafa.",
    "language": "Arabic",
    "greeting": "أهلاً! (Ahlan!)",
    "goodbye": "مع السلامة! (Ma’a salama!)",
    "guide": {
      "name": "Basma",
      "emoji": "🐈",
      "line": "Ahlan! I’m Basma. Cairo is noisy, layered and endlessly historic—look beyond just the pyramids."
    }
  },
  {
    "id": "marrakech",
    "name": "Marrakech",
    "country": "Morocco",
    "continent": "Africa",
    "emoji": "🇲🇦",
    "category": "Culture",
    "lat": 31.6295,
    "lon": -7.9811,
    "timeZone": "Africa/Casablanca",
    "wikiTitle": "Marrakesh",
    "accent": "desert",
    "intro": "Courtyards, souks, gardens and ochre walls create Marrakech’s sensory intensity.",
    "fact": "The medina’s crafts and markets preserve strong links to Amazigh and Moroccan traditions.",
    "knownFor": [
      "Jemaa el-Fnaa",
      "Souks",
      "Riads"
    ],
    "unique": "Behind plain exterior walls, riads often open into highly ornamented private courtyards.",
    "culture": "Amazigh heritage, craft traditions, hospitality and public storytelling shape local identity.",
    "museum": "Dar Si Said, Yves Saint Laurent Museum, Berber/Amazigh collections at Jardin Majorelle",
    "food": "Tagine, couscous, pastilla and mint tea.",
    "language": "Arabic / Amazigh",
    "greeting": "السلام عليكم! (As-salamu alaykum!)",
    "goodbye": "بسلامة! (Bslama!)",
    "guide": {
      "name": "Zina",
      "emoji": "🦊",
      "line": "As-salamu alaykum! I’m Zina. Marrakech hides its most beautiful spaces behind doors and alleyways."
    }
  },
  {
    "id": "nairobi",
    "name": "Nairobi",
    "country": "Kenya",
    "continent": "Africa",
    "emoji": "🇰🇪",
    "category": "Culture",
    "lat": -1.2921,
    "lon": 36.8219,
    "timeZone": "Africa/Nairobi",
    "wikiTitle": "Nairobi",
    "accent": "wild",
    "intro": "A fast-moving East African capital where urban culture meets wildlife and regional history.",
    "fact": "Nairobi National Park sits immediately beside a major capital city.",
    "knownFor": [
      "Nairobi National Park",
      "Creative scene",
      "Gateway to Kenya"
    ],
    "unique": "Skyscrapers and a national park exist within the same metropolitan landscape.",
    "culture": "Kenyan music, food, fashion, tech and many ethnic traditions meet in a highly diverse city.",
    "museum": "Nairobi National Museum, Karen Blixen Museum, Railway Museum",
    "food": "Nyama choma, ugali, sukuma wiki, chapati and Kenyan tea.",
    "language": "Swahili / English",
    "greeting": "Jambo! / Habari!",
    "goodbye": "Kwaheri!",
    "guide": {
      "name": "Kito",
      "emoji": "🦒",
      "line": "Habari! I’m Kito. Nairobi moves fast—but nature, art, food and history are never far away."
    }
  },
  {
    "id": "maasai-mara",
    "name": "Maasai Mara",
    "country": "Kenya",
    "continent": "Africa",
    "emoji": "🇰🇪",
    "category": "Wild",
    "lat": -1.4931,
    "lon": 35.1439,
    "timeZone": "Africa/Nairobi",
    "wikiTitle": "Maasai Mara",
    "accent": "wild",
    "intro": "Open grasslands, river systems and extraordinary wildlife define this Kenyan reserve.",
    "fact": "The Mara ecosystem is part of the larger Serengeti–Mara landscape.",
    "knownFor": [
      "Big cats",
      "Great Migration season",
      "Open savannah"
    ],
    "unique": "Wildlife viewing occurs within a living cultural landscape connected to Maasai communities.",
    "culture": "Maasai pastoral heritage, beadwork, oral traditions and cattle-centered life are important regional traditions.",
    "museum": "Cultural visits are community-based rather than museum-centered; pair wildlife exploration with respectful Maasai-led experiences.",
    "food": "Local Kenyan staples vary by lodge/community; nyama choma and chai are common wider-region favourites.",
    "language": "Maa / Swahili / English",
    "greeting": "Supa! (Maa greeting)",
    "goodbye": "Kwaheri!",
    "guide": {
      "name": "Enkai",
      "emoji": "🦁",
      "line": "Supa! I’m Enkai. Here, the landscape is the main stage—watch carefully and give wildlife space."
    }
  },
  {
    "id": "stone-town",
    "name": "Stone Town",
    "country": "Tanzania",
    "continent": "Africa",
    "emoji": "🇹🇿",
    "category": "Coastal",
    "lat": -6.1622,
    "lon": 39.1921,
    "timeZone": "Africa/Dar_es_Salaam",
    "wikiTitle": "Stone Town",
    "accent": "lagoon",
    "intro": "Narrow lanes, carved doors and coral-stone buildings tell the story of Indian Ocean trade.",
    "fact": "Stone Town reflects centuries of Swahili, Arab, Indian and European cultural exchange.",
    "knownFor": [
      "Carved Zanzibar doors",
      "Swahili heritage",
      "Spice-trade history"
    ],
    "unique": "Its architecture preserves a rare fusion of East African and Indian Ocean influences.",
    "culture": "Swahili language, coastal Islam, taarab music, spice cuisine and public baraza spaces shape local life.",
    "museum": "Palace Museum, Old Fort, Anglican Cathedral/Slave Market heritage site",
    "food": "Zanzibar pizza, biryani, pilau, seafood and spiced tea.",
    "language": "Swahili",
    "greeting": "Karibu! / Jambo!",
    "goodbye": "Kwaheri!",
    "guide": {
      "name": "Pili",
      "emoji": "🐚",
      "line": "Karibu! I’m Pili. Stone Town is a maze—every carved door and alley carries a piece of ocean history."
    }
  },
  {
    "id": "cape-town",
    "name": "Cape Town",
    "country": "South Africa",
    "continent": "Africa",
    "emoji": "🇿🇦",
    "category": "Coastal",
    "lat": -33.9249,
    "lon": 18.4241,
    "timeZone": "Africa/Johannesburg",
    "wikiTitle": "Cape Town",
    "accent": "alpine",
    "intro": "Mountains, ocean, design and layered histories converge around Table Bay.",
    "fact": "Table Mountain forms one of the world’s most recognizable urban natural backdrops.",
    "knownFor": [
      "Table Mountain",
      "Cape coast",
      "Design and food"
    ],
    "unique": "A dramatic mountain ecosystem rises directly beside a major coastal city.",
    "culture": "Cape Town reflects Khoisan, African, Cape Malay, European and global influences.",
    "museum": "District Six Museum, Iziko South African Museum, Zeitz MOCAA",
    "food": "Cape Malay curry, bobotie, braai and seafood.",
    "language": "English / Afrikaans / isiXhosa",
    "greeting": "Molo! / Hello!",
    "goodbye": "Sala kakuhle! / Goodbye!",
    "guide": {
      "name": "Fyn",
      "emoji": "🐧",
      "line": "Molo! I’m Fyn the penguin. Cape Town’s beauty is easy to see—its layered history takes longer to understand."
    }
  },
  {
    "id": "victoria-falls",
    "name": "Victoria Falls",
    "country": "Zimbabwe / Zambia",
    "continent": "Africa",
    "emoji": "🌍",
    "category": "Wild",
    "lat": -17.9243,
    "lon": 25.8572,
    "timeZone": "Africa/Harare",
    "wikiTitle": "Victoria Falls",
    "accent": "wild",
    "intro": "A vast curtain of water drops into a deep gorge on the Zambezi River.",
    "fact": "The local Lozi/Tokalea name Mosi-oa-Tunya means “The Smoke That Thunders.”",
    "knownFor": [
      "Waterfall",
      "Zambezi Gorge",
      "Mosi-oa-Tunya"
    ],
    "unique": "Spray from the falls can rise high enough to create its own misty micro-environment.",
    "culture": "The falls sit within a cross-border cultural landscape connected to communities on both sides of the Zambezi.",
    "museum": "Livingstone Museum in Zambia is a major regional history museum; local heritage experiences vary by side.",
    "food": "Regional dishes include nshima/sadza, grilled meats, vegetables and river fish.",
    "language": "English + regional languages",
    "greeting": "Muli bwanji! / Hello!",
    "goodbye": "Tionana! / See you!",
    "guide": {
      "name": "Mosi",
      "emoji": "💧",
      "line": "Hello! I’m Mosi. You’ll hear Victoria Falls before you fully see it."
    }
  },
  {
    "id": "socotra",
    "name": "Socotra",
    "country": "Yemen",
    "continent": "Asia",
    "emoji": "🇾🇪",
    "category": "Wild",
    "lat": 12.4634,
    "lon": 53.8237,
    "timeZone": "Asia/Aden",
    "wikiTitle": "Socotra",
    "accent": "wild",
    "intro": "Dragon blood trees and remote beaches make Socotra feel like another planet.",
    "fact": "A remarkable share of Socotra’s plants, reptiles and land snails are endemic.",
    "knownFor": [
      "Dragon blood trees",
      "Endemic wildlife",
      "Remote landscapes"
    ],
    "unique": "Its long isolation produced exceptionally high levels of endemism.",
    "culture": "Soqotri language, pastoral traditions and long-adapted land/sea practices remain distinctive.",
    "museum": "Socotra is primarily a natural/cultural landscape rather than a museum destination.",
    "food": "Fish, rice, dates and simple island dishes shaped by available local ingredients.",
    "language": "Soqotri / Arabic",
    "greeting": "Marhaban!",
    "goodbye": "Ma’a salama!",
    "guide": {
      "name": "Dara",
      "emoji": "🌳",
      "line": "Marhaban! I’m Dara. Socotra’s strangest-looking plants are not fantasy—they evolved in isolation."
    }
  },
  {
    "id": "sossusvlei",
    "name": "Sossusvlei",
    "country": "Namibia",
    "continent": "Africa",
    "emoji": "🇳🇦",
    "category": "Desert",
    "lat": -24.7275,
    "lon": 15.2924,
    "timeZone": "Africa/Windhoek",
    "wikiTitle": "Sossusvlei",
    "accent": "desert",
    "intro": "Towering red dunes rise around pale salt-and-clay pans deep inside the Namib.",
    "fact": "The Namib is among the world’s oldest desert environments.",
    "knownFor": [
      "Red dunes",
      "Deadvlei",
      "Desert light"
    ],
    "unique": "The contrast of orange dunes, white pans and dark camel-thorn trees creates an almost graphic landscape.",
    "culture": "The wider Namibian context includes diverse communities and desert-adapted ways of life.",
    "museum": "Best understood through natural history and landscape interpretation rather than conventional museums.",
    "food": "Namibian cuisine includes game meats, braai, maize staples and German-influenced baking in some areas.",
    "language": "English + regional languages",
    "greeting": "Hello!",
    "goodbye": "See you!",
    "guide": {
      "name": "Dune",
      "emoji": "🦎",
      "line": "Hello! I’m Dune. Here, shadows are part of the landscape—visit with your eyes open to shape and light."
    }
  },
  {
    "id": "kyoto",
    "name": "Kyoto",
    "country": "Japan",
    "continent": "Asia",
    "emoji": "🇯🇵",
    "category": "Culture",
    "lat": 35.0116,
    "lon": 135.7681,
    "timeZone": "Asia/Tokyo",
    "wikiTitle": "Kyoto",
    "accent": "snow",
    "intro": "Temples, gardens, crafts and living traditions make Kyoto a cultural heart of Japan.",
    "fact": "Kyoto was Japan’s imperial capital for over a thousand years.",
    "knownFor": [
      "Temples and shrines",
      "Tea culture",
      "Traditional crafts"
    ],
    "unique": "Many practices associated with classical Japanese culture remain part of living institutions here.",
    "culture": "Tea ceremony, flower arrangement, kimono, seasonal festivals, Zen aesthetics and hospitality are deeply rooted.",
    "museum": "Kyoto National Museum, Kyoto International Manga Museum, traditional craft centers",
    "food": "Kaiseki, yudofu, obanzai, matcha sweets and Kyoto vegetables.",
    "language": "Japanese",
    "greeting": "こんにちは! (Konnichiwa!)",
    "goodbye": "またね! (Mata ne!)",
    "guide": {
      "name": "Kumo",
      "emoji": "🦊",
      "line": "Konnichiwa! I’m Kumo. Kyoto is quiet on the surface, but every season, craft and ritual carries meaning."
    }
  },
  {
    "id": "seoul",
    "name": "Seoul",
    "country": "South Korea",
    "continent": "Asia",
    "emoji": "🇰🇷",
    "category": "Culture",
    "lat": 37.5665,
    "lon": 126.978,
    "timeZone": "Asia/Seoul",
    "wikiTitle": "Seoul",
    "accent": "rose",
    "intro": "Royal palaces, mountains, markets and digital culture collide in a fast-moving capital.",
    "fact": "Seoul preserves major Joseon-era palaces within one of the world’s largest metropolitan areas.",
    "knownFor": [
      "Palaces",
      "K-culture",
      "Street food"
    ],
    "unique": "Historic hanok neighbourhoods and cutting-edge digital districts exist side-by-side.",
    "culture": "Confucian heritage, communal dining, café culture, music, fashion and technology all shape the city.",
    "museum": "National Museum of Korea, Seoul Museum of History, National Folk Museum",
    "food": "Kimchi, tteokbokki, bibimbap, Korean barbecue.",
    "language": "Korean",
    "greeting": "안녕하세요! (Annyeonghaseyo!)",
    "goodbye": "안녕히 가세요! (Annyeonghi gaseyo!)",
    "guide": {
      "name": "Bomi",
      "emoji": "🐯",
      "line": "Annyeonghaseyo! I’m Bomi. Seoul changes block by block—from palace walls to neon streets."
    }
  },
  {
    "id": "bangkok",
    "name": "Bangkok",
    "country": "Thailand",
    "continent": "Asia",
    "emoji": "🇹🇭",
    "category": "Culture",
    "lat": 13.7563,
    "lon": 100.5018,
    "timeZone": "Asia/Bangkok",
    "wikiTitle": "Bangkok",
    "accent": "sunset",
    "intro": "Temples, markets, river life and street food make Bangkok intensely energetic.",
    "fact": "Bangkok’s historic core contains major royal and religious sites alongside dense modern neighbourhoods.",
    "knownFor": [
      "Temples",
      "Street food",
      "Markets"
    ],
    "unique": "River, canal, road and elevated transit systems create many overlapping versions of the city.",
    "culture": "Buddhist traditions, markets, food culture and respect-based etiquette shape daily interactions.",
    "museum": "Bangkok National Museum, Museum Siam, Jim Thompson House",
    "food": "Pad thai, tom yum, green curry, mango sticky rice.",
    "language": "Thai",
    "greeting": "สวัสดี! (Sawasdee!)",
    "goodbye": "ลาก่อน! (La gorn!)",
    "guide": {
      "name": "Mali",
      "emoji": "🐘",
      "line": "Sawasdee! I’m Mali. Bangkok is best understood through its river, temples and food stalls—not just traffic."
    }
  },
  {
    "id": "singapore",
    "name": "Singapore",
    "country": "Singapore",
    "continent": "Asia",
    "emoji": "🇸🇬",
    "category": "Culture",
    "lat": 1.3521,
    "lon": 103.8198,
    "timeZone": "Asia/Singapore",
    "wikiTitle": "Singapore",
    "accent": "lagoon",
    "intro": "A dense city-state where heritage districts, gardens, hawker centres and futuristic architecture meet.",
    "fact": "Singapore’s food culture reflects Chinese, Malay, Indian and Peranakan influences.",
    "knownFor": [
      "Hawker food",
      "Gardens by the Bay",
      "Multicultural districts"
    ],
    "unique": "Highly planned urbanism coexists with distinctive historic neighbourhoods and street-food traditions.",
    "culture": "Multilingual, multicultural everyday life is central to Singaporean identity.",
    "museum": "National Gallery Singapore, Asian Civilisations Museum, National Museum of Singapore",
    "food": "Hainanese chicken rice, laksa, satay, kaya toast.",
    "language": "English / Malay / Mandarin / Tamil",
    "greeting": "Hello! / Selamat datang!",
    "goodbye": "Jumpa lagi!",
    "guide": {
      "name": "Milo",
      "emoji": "🦦",
      "line": "Hello! I’m Milo the otter. Singapore is compact, but every neighbourhood tells a different cultural story."
    }
  },
  {
    "id": "bali",
    "name": "Bali",
    "country": "Indonesia",
    "continent": "Asia",
    "emoji": "🇮🇩",
    "category": "Coastal",
    "lat": -8.4095,
    "lon": 115.1889,
    "timeZone": "Asia/Makassar",
    "wikiTitle": "Bali",
    "accent": "wild",
    "intro": "Temples, rice terraces, beaches and village arts shape Bali’s distinctive island culture.",
    "fact": "Balinese Hindu traditions are deeply woven into daily offerings, festivals and architecture.",
    "knownFor": [
      "Temples",
      "Rice terraces",
      "Dance and crafts"
    ],
    "unique": "Ritual life is visibly integrated into homes, streets, temples and agricultural landscapes.",
    "culture": "Balinese Hindu ceremonies, gamelan, dance, carving, painting and community banjar life are central.",
    "museum": "Museum Puri Lukisan, Agung Rai Museum of Art, Bali Museum",
    "food": "Nasi campur, babi guling, sate lilit and lawar.",
    "language": "Balinese / Indonesian",
    "greeting": "Om Swastiastu!",
    "goodbye": "Om Shanti Shanti Shanti Om.",
    "guide": {
      "name": "Sari",
      "emoji": "🐒",
      "line": "Om Swastiastu! I’m Sari. Bali’s beauty makes more sense when you notice how art and ritual are part of everyday life."
    }
  },
  {
    "id": "sydney",
    "name": "Sydney",
    "country": "Australia",
    "continent": "Oceania",
    "emoji": "🇦🇺",
    "category": "Coastal",
    "lat": -33.8688,
    "lon": 151.2093,
    "timeZone": "Australia/Sydney",
    "wikiTitle": "Sydney",
    "accent": "lagoon",
    "intro": "Harbour icons, beaches, creative neighbourhoods and Aboriginal heritage shape Sydney.",
    "fact": "Sydney Harbour is both a spectacular natural harbour and a major cultural landscape.",
    "knownFor": [
      "Opera House",
      "Harbour Bridge",
      "Beaches"
    ],
    "unique": "A major global city is structured around coves, headlands, beaches and harbour ferries.",
    "culture": "Contemporary Sydney is highly multicultural, while Aboriginal cultures of the region predate the city by tens of thousands of years.",
    "museum": "Australian Museum, Art Gallery of NSW, Museum of Sydney",
    "food": "Seafood, café brunch, meat pies and globally influenced dining.",
    "language": "English + Aboriginal languages of Country",
    "greeting": "G’day!",
    "goodbye": "See ya!",
    "guide": {
      "name": "Kora",
      "emoji": "🦜",
      "line": "G’day! I’m Kora. Sydney’s postcard views are only the beginning—harbour, Country and neighbourhoods tell the fuller story."
    }
  },
  {
    "id": "auckland",
    "name": "Auckland",
    "country": "New Zealand",
    "continent": "Oceania",
    "emoji": "🇳🇿",
    "category": "Coastal",
    "lat": -36.8509,
    "lon": 174.7645,
    "timeZone": "Pacific/Auckland",
    "wikiTitle": "Auckland",
    "accent": "lagoon",
    "intro": "Volcanic cones, harbours and a strong Māori and Pacific cultural presence define Tāmaki Makaurau.",
    "fact": "Auckland sits across a volcanic field dotted with historic cones.",
    "knownFor": [
      "Two harbours",
      "Māori culture",
      "Volcanic landscape"
    ],
    "unique": "The city combines Pacific urban life with volcanic geography and island-filled waters.",
    "culture": "Māori and Pacific cultures are foundational to Auckland’s identity, alongside a highly diverse migrant population.",
    "museum": "Auckland War Memorial Museum, Auckland Art Gallery Toi o Tāmaki, New Zealand Maritime Museum",
    "food": "Hāngī-inspired cuisine, seafood, Pacific flavours and modern multicultural dining.",
    "language": "English / te reo Māori",
    "greeting": "Kia ora!",
    "goodbye": "Ka kite!",
    "guide": {
      "name": "Tui",
      "emoji": "🐦",
      "line": "Kia ora! I’m Tui. In Tāmaki Makaurau, look for the story of the land as much as the skyline."
    }
  },
  {
    "id": "banff",
    "name": "Banff",
    "country": "Canada",
    "continent": "North America",
    "emoji": "🇨🇦",
    "category": "Mountains",
    "lat": 51.1784,
    "lon": -115.5708,
    "timeZone": "America/Edmonton",
    "wikiTitle": "Banff National Park",
    "accent": "alpine",
    "intro": "Turquoise lakes, dramatic peaks and forests define this Rocky Mountain destination.",
    "fact": "Banff became Canada’s first national park in 1885.",
    "knownFor": [
      "Rocky Mountains",
      "Turquoise lakes",
      "Wildlife"
    ],
    "unique": "Glacial geology creates intensely coloured lakes beneath sharp mountain ranges.",
    "culture": "Mountain-town culture intersects with Indigenous histories and conservation traditions.",
    "museum": "Whyte Museum of the Canadian Rockies, Banff Park Museum",
    "food": "Canadian comfort food, game dishes, poutine and regional craft beverages.",
    "language": "English / French",
    "greeting": "Hello! / Bonjour!",
    "goodbye": "See you! / Au revoir!",
    "guide": {
      "name": "Maple",
      "emoji": "🦌",
      "line": "Hello! I’m Maple. Banff is gorgeous—but the best visitor is one who treats wildlife and trails with respect."
    }
  },
  {
    "id": "lofoten",
    "name": "Lofoten",
    "country": "Norway",
    "continent": "Europe",
    "emoji": "🇳🇴",
    "category": "Mountains",
    "lat": 68.2089,
    "lon": 13.9154,
    "timeZone": "Europe/Oslo",
    "wikiTitle": "Lofoten",
    "accent": "arctic",
    "intro": "Sharp peaks rise directly from the sea beside fishing villages and Arctic beaches.",
    "fact": "Cod fisheries have shaped Lofoten’s economy and coastal culture for centuries.",
    "knownFor": [
      "Fishing villages",
      "Stockfish",
      "Arctic mountains"
    ],
    "unique": "Steep alpine-looking peaks rise almost directly out of the ocean.",
    "culture": "Fishing heritage, crafts and contemporary art all remain visible across small villages.",
    "museum": "Lofotr Viking Museum, Lofoten Museum, SKREI, KaviarFactory",
    "food": "Stockfish, cod, lamb and cloudberries.",
    "language": "Norwegian",
    "greeting": "Hei!",
    "goodbye": "Ha det!",
    "guide": {
      "name": "Torsk",
      "emoji": "🐟",
      "line": "Hei! I’m Torsk. Lofoten’s scenery is dramatic, but fishing culture is what made these islands liveable."
    }
  },
  {
    "id": "mexico-city",
    "name": "Mexico City",
    "country": "Mexico",
    "continent": "North America",
    "emoji": "🇲🇽",
    "category": "Culture",
    "lat": 19.4326,
    "lon": -99.1332,
    "timeZone": "America/Mexico_City",
    "wikiTitle": "Mexico City",
    "accent": "rose",
    "intro": "Ancient foundations, murals, markets, museums and vast neighbourhoods fill one of the Americas’ great capitals.",
    "fact": "Modern Mexico City was built over the Mexica capital Tenochtitlan.",
    "knownFor": [
      "Museums",
      "Muralism",
      "Street food"
    ],
    "unique": "Pre-Hispanic archaeology, colonial architecture and contemporary megacity life overlap physically.",
    "culture": "Markets, public plazas, mural art, music and regional cuisines converge in the capital.",
    "museum": "National Museum of Anthropology, Frida Kahlo Museum, Museo del Templo Mayor",
    "food": "Tacos al pastor, tamales, tlacoyos, churros.",
    "language": "Spanish",
    "greeting": "¡Hola!",
    "goodbye": "¡Hasta luego!",
    "guide": {
      "name": "Xolo",
      "emoji": "🐕",
      "line": "¡Hola! I’m Xolo. Mexico City has layers—sometimes literally, with older cities beneath the streets."
    }
  },
  {
    "id": "new-orleans",
    "name": "New Orleans",
    "country": "United States",
    "continent": "North America",
    "emoji": "🇺🇸",
    "category": "Culture",
    "lat": 29.9511,
    "lon": -90.0715,
    "timeZone": "America/Chicago",
    "wikiTitle": "New Orleans",
    "accent": "sunset",
    "intro": "Music, Creole food, parades and distinctive architecture give New Orleans an unmatched identity.",
    "fact": "Jazz emerged from the city’s complex blend of African American, Caribbean, European and local traditions.",
    "knownFor": [
      "Jazz",
      "Mardi Gras",
      "Creole cuisine"
    ],
    "unique": "Music spills from formal venues into streets, parades and neighbourhood traditions.",
    "culture": "Second lines, brass bands, Creole traditions and festival culture are central.",
    "museum": "The National WWII Museum, New Orleans Jazz Museum, Backstreet Cultural Museum",
    "food": "Gumbo, jambalaya, po’boys, beignets.",
    "language": "English",
    "greeting": "Hey y’all!",
    "goodbye": "See y’all later!",
    "guide": {
      "name": "Beau",
      "emoji": "🐊",
      "line": "Hey y’all! I’m Beau. In New Orleans, music is not background noise—it’s part of civic life."
    }
  },
  {
    "id": "buenos-aires",
    "name": "Buenos Aires",
    "country": "Argentina",
    "continent": "South America",
    "emoji": "🇦🇷",
    "category": "Culture",
    "lat": -34.6037,
    "lon": -58.3816,
    "timeZone": "America/Argentina/Buenos_Aires",
    "wikiTitle": "Buenos Aires",
    "accent": "rose",
    "intro": "Tango, cafés, theatres and grand boulevards give Buenos Aires its expressive character.",
    "fact": "Tango is deeply tied to the city’s identity and neighbourhood history.",
    "knownFor": [
      "Tango",
      "Theatre",
      "Café culture"
    ],
    "unique": "European-influenced architecture meets distinctly porteño music, football and street life.",
    "culture": "Tango, late dinners, mate, literature, football and neighbourhood cafés are major social markers.",
    "museum": "MALBA, Museo Nacional de Bellas Artes, Carlos Gardel House Museum, World Tango Museum",
    "food": "Empanadas, asado, medialunas and dulce de leche.",
    "language": "Spanish",
    "greeting": "¡Hola! ¿Cómo va?",
    "goodbye": "¡Chau!",
    "guide": {
      "name": "Lola",
      "emoji": "💃",
      "line": "¡Hola! I’m Lola. Buenos Aires has rhythm—even its cafés and late-night streets seem choreographed."
    }
  },
  {
    "id": "cusco",
    "name": "Cusco",
    "country": "Peru",
    "continent": "South America",
    "emoji": "🇵🇪",
    "category": "Culture",
    "lat": -13.5319,
    "lon": -71.9675,
    "timeZone": "America/Lima",
    "wikiTitle": "Cusco",
    "accent": "alpine",
    "intro": "Inca stonework, colonial architecture and Andean traditions converge in a high-altitude city.",
    "fact": "Cusco was the capital of the Inca Empire.",
    "knownFor": [
      "Inca masonry",
      "Andean culture",
      "Gateway to the Sacred Valley"
    ],
    "unique": "Spanish colonial buildings often sit directly on remarkably fitted Inca stone foundations.",
    "culture": "Quechua heritage, Catholic-Andean syncretism, textiles, festivals and market traditions remain visible.",
    "museum": "Museo Inka, Museo de Arte Precolombino, Qorikancha site museum",
    "food": "Cuy, chiri uchu, quinoa dishes and Andean potatoes.",
    "language": "Spanish / Quechua",
    "greeting": "Rimaykullayki! (Quechua greeting)",
    "goodbye": "Tupananchiskama! (Until we meet again)",
    "guide": {
      "name": "Inti",
      "emoji": "🦙",
      "line": "Rimaykullayki! I’m Inti. Cusco rewards slow looking—the stonework tells you how many histories occupy one street."
    }
  },
  {
    "id": "machu-picchu",
    "name": "Machu Picchu",
    "country": "Peru",
    "continent": "South America",
    "emoji": "🇵🇪",
    "category": "Mountains",
    "lat": -13.1631,
    "lon": -72.545,
    "timeZone": "America/Lima",
    "wikiTitle": "Machu Picchu",
    "accent": "alpine",
    "intro": "An Inca citadel sits high among steep Andean peaks and cloud-forest slopes.",
    "fact": "The site combines architecture, terraces and mountain geography with remarkable precision.",
    "knownFor": [
      "Inca citadel",
      "Terraces",
      "Mountain setting"
    ],
    "unique": "Built on a narrow ridge, the site integrates ceremonial, residential and agricultural spaces.",
    "culture": "Its meaning is rooted in Inca history and the wider Quechua cultural landscape.",
    "museum": "Manuel Chávez Ballón Site Museum near Machu Picchu Pueblo",
    "food": "Regional Andean cuisine includes potatoes, corn, quinoa and trout.",
    "language": "Spanish / Quechua",
    "greeting": "Rimaykullayki!",
    "goodbye": "Tupananchiskama!",
    "guide": {
      "name": "Killa",
      "emoji": "🦙",
      "line": "Rimaykullayki! I’m Killa. Machu Picchu is impressive because architecture and mountain terrain were designed together."
    }
  },
  {
    "id": "lencois",
    "name": "Lençóis Maranhenses",
    "country": "Brazil",
    "continent": "South America",
    "emoji": "🇧🇷",
    "category": "Rare",
    "lat": -2.5333,
    "lon": -43.1167,
    "timeZone": "America/Fortaleza",
    "wikiTitle": "Lençóis Maranhenses National Park",
    "accent": "lagoon",
    "intro": "White dunes fill with seasonal freshwater lagoons after the rains.",
    "fact": "Despite its desert-like appearance, the region receives significant seasonal rainfall.",
    "knownFor": [
      "White dunes",
      "Seasonal lagoons",
      "Surreal landscapes"
    ],
    "unique": "Freshwater pools appear between dunes, transforming the landscape with the seasons.",
    "culture": "Nearby communities have adapted life, fishing and movement to the rhythms of dunes and water.",
    "museum": "This is primarily a natural landscape; local interpretation and community guides offer the richest context.",
    "food": "Northeastern Brazilian dishes include seafood, rice, beans, tapioca and regional fruits.",
    "language": "Portuguese",
    "greeting": "Olá!",
    "goodbye": "Tchau!",
    "guide": {
      "name": "Lua",
      "emoji": "🦜",
      "line": "Olá! I’m Lua. Lençóis changes personality with the rain—timing completely transforms what you see."
    }
  },
  {
    "id": "rio",
    "name": "Rio de Janeiro",
    "country": "Brazil",
    "continent": "South America",
    "emoji": "🇧🇷",
    "category": "Coastal",
    "lat": -22.9068,
    "lon": -43.1729,
    "timeZone": "America/Sao_Paulo",
    "wikiTitle": "Rio de Janeiro",
    "accent": "lagoon",
    "intro": "Mountains, beaches, samba and dense neighbourhoods create one of the world’s most recognizable urban landscapes.",
    "fact": "Rio’s urban setting is shaped by dramatic granite peaks between sea and city.",
    "knownFor": [
      "Copacabana",
      "Samba",
      "Carnival"
    ],
    "unique": "Beaches, rainforest-covered mountains and dense urban neighbourhoods sit astonishingly close together.",
    "culture": "Samba, carnival traditions, football, beach culture and Afro-Brazilian influences are central.",
    "museum": "Museu do Amanhã, Museu de Arte do Rio, National Historical Museum",
    "food": "Feijoada, pão de queijo, grilled meats and açaí.",
    "language": "Portuguese",
    "greeting": "Oi!",
    "goodbye": "Tchau!",
    "guide": {
      "name": "Bela",
      "emoji": "🦜",
      "line": "Oi! I’m Bela. Rio is not one view—it’s mountains, music, beaches and neighbourhoods layered together."
    }
  },
  {
    "id": "dubrovnik",
    "name": "Dubrovnik",
    "country": "Croatia",
    "continent": "Europe",
    "emoji": "🇭🇷",
    "category": "Coastal",
    "lat": 42.6507,
    "lon": 18.0944,
    "timeZone": "Europe/Zagreb",
    "wikiTitle": "Dubrovnik",
    "accent": "lagoon",
    "intro": "Stone walls, terracotta roofs and the Adriatic define this historic maritime city.",
    "fact": "Dubrovnik was the center of the maritime Republic of Ragusa.",
    "knownFor": [
      "City walls",
      "Adriatic views",
      "Old Town"
    ],
    "unique": "Its intact fortifications make the historic core feel physically distinct from the surrounding coast.",
    "culture": "Maritime history, Catholic festivals, local dialect and Mediterranean food traditions shape identity.",
    "museum": "Cultural History Museum in Rector’s Palace, Maritime Museum, War Photo Limited",
    "food": "Black risotto, seafood, rozata and olive-oil based dishes.",
    "language": "Croatian",
    "greeting": "Bok!",
    "goodbye": "Doviđenja!",
    "guide": {
      "name": "Maro",
      "emoji": "🕊️",
      "line": "Bok! I’m Maro. Dubrovnik’s walls are impressive—but its history as a trading republic is the deeper story."
    }
  },
  {
    "id": "singapore-gardens",
    "name": "Gardens by the Bay",
    "country": "Singapore",
    "continent": "Asia",
    "emoji": "🇸🇬",
    "category": "Rare",
    "lat": 1.2816,
    "lon": 103.8636,
    "timeZone": "Asia/Singapore",
    "wikiTitle": "Gardens by the Bay",
    "accent": "wild",
    "intro": "Futuristic conservatories and Supertrees turn horticulture into a sci-fi cityscape.",
    "fact": "The gardens combine large-scale horticulture with climate-controlled conservatories.",
    "knownFor": [
      "Supertrees",
      "Cloud Forest",
      "Flower Dome"
    ],
    "unique": "Plants are presented through architecture and environmental engineering at city scale.",
    "culture": "The attraction reflects Singapore’s broader identity as a highly planned 'City in Nature'.",
    "museum": "Not a conventional museum; the conservatories function as immersive botanical interpretation spaces.",
    "food": "Nearby hawker and city dining offers Singapore’s broad multicultural food traditions.",
    "language": "English / Malay",
    "greeting": "Welcome! / Selamat datang!",
    "goodbye": "See you! / Jumpa lagi!",
    "guide": {
      "name": "Sprig",
      "emoji": "🌱",
      "line": "Welcome! I’m Sprig. This is what happens when a botanical garden borrows ideas from science fiction."
    }
  },
  {
    "id": "marrakech-medina",
    "name": "Marrakech Medina",
    "country": "Morocco",
    "continent": "Africa",
    "emoji": "🇲🇦",
    "category": "Culture",
    "lat": 31.6315,
    "lon": -7.989,
    "timeZone": "Africa/Casablanca",
    "wikiTitle": "Medina of Marrakesh",
    "accent": "desert",
    "intro": "A dense historic quarter of souks, courtyards, mosques and public squares.",
    "fact": "The medina developed as the historic core of an imperial Moroccan city.",
    "knownFor": [
      "Souks",
      "Jemaa el-Fnaa",
      "Crafts"
    ],
    "unique": "The contrast between busy public lanes and serene interior courtyards is one of its defining spatial experiences.",
    "culture": "Craft guilds, storytelling, food stalls, music and hospitality remain central to the medina atmosphere.",
    "museum": "Dar Si Said and nearby heritage museums illuminate craft and domestic traditions.",
    "food": "Tagine, tanjia, harira and mint tea.",
    "language": "Arabic / Amazigh",
    "greeting": "Ahlan wa sahlan!",
    "goodbye": "Bslama!",
    "guide": {
      "name": "Riad",
      "emoji": "🪬",
      "line": "Ahlan wa sahlan! I’m Riad. In the medina, the quietest courtyards often sit behind the busiest streets."
    }
  }
];

export const categories = ['All','Coastal','Wild','Culture','Desert','Mountains','Rare'];
